docs/AboutUs.md

Update AboutUs page - Cassandra

---

docs/AboutUs.md

Update AboutUs page - Jiawei

---

docs/_config.yml
docs/_sass/minima/_base.scss

Update set-wide settings

---

docs/DeveloperGuide.md

Developer guide: update non-functional requirements

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/person/Detail.java
src/main/java/seedu/address/model/person/Person.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java

Add Feature Follow Up

---

src/main/java/seedu/address/ui/MainWindow.java

Fix exit acknowledgement not showing

---

src/main/java/seedu/address/model/person/Age.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java

Update Age class to check age constraints and tests for invalid age

---

src/main/java/seedu/address/logic/LogicManager.java
src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java

Update save error messages

---

src/main/resources/view/DarkTheme.css
src/main/resources/view/PersonListCard.fxml

Fixes #72 
Study group tags are now displayed properly in person cards.

MVP - Fix UI bugs

---

docs/diagrams/ModelClassDiagram.puml

Update UML diagram for ModelClassDiagram

---

docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml
docs/diagrams/StorageClassDiagram.puml

Alpha version - Update UML diagrams (ModelClassDiagram, BetterModelClassDiagram, StorageClassDiagram)

---

src/main/java/seedu/address/logic/LogicManager.java

Fix save feature bugs

---

src/main/java/seedu/address/logic/commands/EditCommand.java

Fixes #99 
Tweaked formats to ensure consistency with previously standardized messages.

Alpha version - Message standardization (edit feature)

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/model/person/Name.java
src/test/java/seedu/address/model/person/NameTest.java

Fixes #101
- Tweak Javadoc comments to ensure alignment with current project.
- Tweak formats to ensure consistency with previously standardized messages.

Alpha version - Code standardization (miscellaneous)

---

src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/ExportCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ExportCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/data/ExportCommandTest/expectedExportFilteredList.txt
src/test/data/ExportCommandTest/expectedExportUnfilteredList.txt
src/test/data/ExportCommandTest/validExportFile.txt
src/test/data/ExportCommandTest/validExportFile2.txt
src/test/java/seedu/address/logic/commands/ExportCommandTest.java
src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java

Alpha version - Add export feature

---

src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java

Fix delete parse message

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/model/person/Gender.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java

Alpha version - Edit: remove tags

---

src/main/java/seedu/address/logic/commands/ClearCommand.java
src/test/data/ExportCommandTest/expectedExportFilteredList.txt
src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/commands/ExportCommandTest.java

Add clear command for filtered list functionality

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java

Fixes #122 
find a/35 40-60 returns all persons who are 35 or whose ages are between 40 and 60
delete 1 3-5 deletes the 1st and persons from the 3th to the 5th
edge cases

Alpha Version - Handle range for find and delete command

---

README.md

Fixes #134 
Updated link for the **CI status badge**.

Alpha version - ReadMe

---

docs/index.md

Fixes #136 
- Links for the **CI status badge** and **codecov** have been updated.
- Content has been updated to match current project.

Alpha version - index.md

---

src/main/java/seedu/address/ui/HelpWindow.java
src/main/resources/view/HelpWindow.css
src/main/resources/view/HelpWindow.fxml

Fixes #128 
Users can now directly access the user guide, by clicking on the hyperlink shown in the `help` window.

Alpha version - Help feature

---

docs/AboutUs.md
docs/team/jiawei.md
docs/team/kayhian.md
docs/team/kexin.md
docs/team/prisha.md
docs/team/sanchita.md

Fixes #132
Created separate `.md` files for each member's portfolio (to be updated individually).

Alpha version - About Us

---

src/main/java/seedu/address/logic/parser/FindCommandParser.java

Fixes #153 
Expand check to detect duplicate study group tag prefixs `/t`.

Add check to prevent duplicate input fields

---

docs/UserGuide.md

Update add and delete commands in UG

---

src/test/data/ExportCommandTest/expectedExportFilteredList.txt
src/test/data/ExportCommandTest/expectedExportUnfilteredList.txt
src/test/data/ExportCommandTest/validExportFile.txt
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/testutil/TypicalPersons.java

Fixes #140
Fixes #141 
Updated JUnit test files and test data such that emails of typical persons match current project context.

Alpha version - Email standardization (Test)

---

src/test/java/seedu/address/model/tag/StudyGroupTagTest.java

Alpha Version - Add test case for StudyGroupTag

---

src/main/java/seedu/address/model/person/Email.java
src/test/java/seedu/address/model/person/PersonTest.java

Alpha version - Make email equals method case insensitive

---

src/main/resources/view/DarkTheme.css

Alpha Version - Clicking Person card unwanted appearence

---

src/main/java/seedu/address/ui/MainWindow.java

Alpha Version - Punctuation inconsistencies: UI 2

---

src/main/java/seedu/address/ui/UiManager.java

Alpha Version - Punctuation inconsistencies: UI 1

---

src/main/java/seedu/address/logic/LogicManager.java

Alpha Version - Punctuation inconsistencies: Logic

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/model/person/Email.java
src/test/java/seedu/address/model/person/PersonTest.java

Alpha version - fix long success messages for add, delete, edit

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/ExportCommand.java
src/main/java/seedu/address/logic/parser/ExportCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java

Alpha version - export to txt format only

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/ExportCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/parser/ExportCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/data/ExportCommandTest/validExportFile.txt
src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java

Alpha version - fix punctuation for commands

---

docs/UserGuide.md

Update UG list, clear, export

---

docs/DeveloperGuide.md

Update DG user stories

---

docs/DeveloperGuide.md

Update DG effort

---

docs/DeveloperGuide.md

Alpha version - Update DG fix alignment

---

src/main/java/seedu/address/logic/commands/ExportCommand.java

Modify export command example

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/data/ExportCommandTest/validExportFile.txt
src/test/java/seedu/address/logic/commands/EditCommandTest.java

Alpha version - Edit command error message

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java

Modify delete error message to include range

---

README.md

Add new features to feature list in README and mark all implemented features as done

Update features in README

---

docs/DeveloperGuide.md

Fixes #219 
Add UC16 - Clear listed persons, UC17 - Exit
Add manual testing instructions for clear command
Add AB3 link to acknowledgements

Update acknowledgements, use cases and testing in DG

---

docs/DeveloperGuide.md

Fixes #225 
UC06 (Find persons by criteria) has its extensions' steps swapped.

Fix bug in Use Case

---

docs/team/prisha.md
src/main/java/seedu/address/MainApp.java

Fixes #229 
Update version number to v1.5 and update my contributions page

Update version number and my contributions page

---

src/main/java/seedu/address/ui/CommandBox.java
src/main/resources/view/CommandBox.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml

Fixes #232 
Reverts AY2425S1-CS2103T-F08-2/tp#227 due to unexpected bug caused by wrapping

Revert "Alpha Version - Command Box too Short"

---

docs/UserGuide.md

Fixes #233 
Change AddressBook to ResearchRoster in "Editing the data file" warning

Fix bug in UG

---

docs/DeveloperGuide.md

Add page break to DG for formatting

---

src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/CommandBox.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml

Fix text wrapping issue

---

src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/CommandBox.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml

Reverts AY2425S1-CS2103T-F08-2/tp#309
PR #309 violated the feature freeze guidelines, thus we reverted the PR to stick within the guidelines and not incur penalty

Revert "Fix text wrapping issue"

---

README.md

ReadMe: Remove repeated content

---

docs/DeveloperGuide.md

Fixes #250 
Fixes #283 
Fixes #290 
Fixes #293 
See separate commits for targeted changes.

DG: Fix bugs

---

src/main/java/seedu/address/logic/commands/ClearCommand.java

Widen message for confirm clearing

---

src/main/java/seedu/address/commons/core/GuiSettings.java
src/main/java/seedu/address/commons/core/LogsCenter.java
src/main/java/seedu/address/commons/util/ConfigUtil.java
src/main/java/seedu/address/commons/util/FileUtil.java
src/main/java/seedu/address/commons/util/JsonUtil.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/person/Age.java
src/main/java/seedu/address/model/person/Detail.java
src/main/java/seedu/address/model/person/Email.java
src/main/java/seedu/address/model/person/Gender.java
src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/UniqueSortedPersonList.java
src/main/java/seedu/address/model/person/predicates/AgeContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/predicates/GenderMatchesKeywordsPredicate.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/ResultDisplay.java
src/main/java/seedu/address/ui/StatusBarFooter.java

Refine Javadoc comments

---

src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AssignCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/Command.java
src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/ConfirmClearCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/ExportCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
src/main/java/seedu/address/logic/parser/AssignCommandParser.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/Prefix.java

Added javadoc headers to make code better-documented

Refine Javadoc comments: Logic component

---

docs/team/wujiaweijoanna.md

Update md doc

---

docs/UserGuide.md

Justify duplicate emails, specify proper email format, add links

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/ExportCommand.java
src/main/java/seedu/address/logic/parser/ExportCommandParser.java

fixes #336 
Make the instructions for export more clear that you can only export to existing directories

Refine UG export command
